<?xml version="1.0" encoding="UTF-8"?><testrun name="FibonacciTest" project="Fibonacci" tests="10" started="10" failures="1" errors="0" ignored="0">
  <testsuite name="com.capgemini.fibonacci.FibonacciTest" time="0.05">
    <testcase name="testsResultOutOfRangeExceptionMessage" classname="com.capgemini.fibonacci.FibonacciTest" time="0.032"/>
    <testcase name="shouldReturnOneForSecondElementOfFibonacci" classname="com.capgemini.fibonacci.FibonacciTest" time="0.0"/>
    <testcase name="shouldReturnValueOfGivenElementOfFibonacci" classname="com.capgemini.fibonacci.FibonacciTest" time="0.001"/>
    <testcase name="shouldReturnValueOfFibonacciForBigInteger" classname="com.capgemini.fibonacci.FibonacciTest" time="0.0"/>
    <testcase name="testsIllegalArgumentExceptionMessageForZero" classname="com.capgemini.fibonacci.FibonacciTest" time="0.001"/>
    <testcase name="shouldThrowIllegalArgumentExceptionForNegativeArgument" classname="com.capgemini.fibonacci.FibonacciTest" time="0.001"/>
    <testcase name="shouldThrowResultOutOfRangeExceptionForElementsTooBigForLong" classname="com.capgemini.fibonacci.FibonacciTest" time="0.01">
      <failure>java.lang.AssertionError: Expected exception: com.capgemini.fibonacci.ResultOutOfRangeException&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)&#13;
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)&#13;
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="shouldThrowIllegalArgumentExceptionForZero" classname="com.capgemini.fibonacci.FibonacciTest" time="0.001"/>
    <testcase name="shouldReturnOneForFirstElementOfFinbonacci" classname="com.capgemini.fibonacci.FibonacciTest" time="0.001"/>
    <testcase name="testsIllegalArgumentExceptionMessageForNegativeArgument" classname="com.capgemini.fibonacci.FibonacciTest" time="0.002"/>
  </testsuite>
</testrun>
